# Generated by Django 2.1.4 on 2018-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='fun_resp_dep',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='fun_dep_id',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fun_dep_id',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
    ]
