# Generated by Django 2.1.4 on 2018-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_nome', models.CharField(max_length=50)),
                ('std_descricao', models.CharField(max_length=100)),
                ('std_conslusivo', models.BooleanField(default=False)),
            ],
        ),
    ]
