# Generated by Django 2.1.4 on 2018-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_nome', models.CharField(max_length=30)),
                ('grau_descricao', models.CharField(max_length=60)),
                ('grau_urgencia', models.IntegerField()),
            ],
        ),
    ]
